### PR TITLE
add theia-full to the list of available IDE runtimes

### PR DESCRIPTION
**Pull request by rberrelleza**
as requested by the community

### CODE REVIEW

**Review by pchico83 — APPROVED** [review]

**Comment by rberrelleza** [comment]
there are some user id issues that I'm looking into.

**Comment by pchico83** [comment]
@rberrelleza what's the state of this? can it be merged?

**Comment by rberrelleza** [comment]
> @rberrelleza what's the state of this? can it be merged?

no, we should retest it.

**Comment by rberrelleza** [comment]
theia-full is a 3.4GB  pull, should be have it in cloud? @pchico83

**Review by pchico83 — APPROVED** [review]

**Pull request merged**
