### PR TITLE
Upgrade to latest flux v1 chart

### PR DESCRIPTION
**Pull request by kingdonb**
The Helm Operator has upgrades too, but I'm going to work on that separately as it will (may?) require coordination to upgrade the CRD server-side / in okteto cloud or enterprise.

I'm second-guessing that now because I've read the changelogs and it does not appear that any Helm Operator releases have required a CRD upgrade since 1.0 (which you've already included in your chart).

That would make sense, CRD shouldn't change after GA, (but it doesn't jibe with my memory of what people have reported having issues with. Maybe they upgraded from a version that was Pre-1.0 and just didn't tell me.)

We should verify the CRDs are current as some silent or surprising failures are possible if a version of Helm Operator that is too new is used with a CRD that is too old. This is not a big deal with Helm Operator, but it will become important with the next version Helm Controller and its companions Flux, which use more CRDs. That is a breaking upgrade and a new (separate) CRD which is addressed at the top of the [CHANGELOG notes](https://github.com/fluxcd/helm-operator/blob/master/CHANGELOG.md) for Helm Operator.

This PR only upgrade Flux v1 to 1.6.2, which is the current chart.

Flux v1 and v2 can run side by side on the same cluster, it should be possible to support both. (This PR only approaches making Flux v1 a current release, since there are bugs in 1.19.0 flux daemon and I've had to upgrade my Flux instance on Okteto Cloud in order to get ahead of them.)

### CODE REVIEW

**Comment by kingdonb** [comment]
Addresses #109 (but does not close it)

To close #109, we should add another PR (or add into this one before it merges), an upgrade of Helm Operator to the latest version, currently 1.2.0... and also open a separate issue to track the support of Flux v2.

Since Flux v2 does not provide helm charts, it will have to be a PR/issue against some other repo (as this is the charts repo)

**Review by rberrelleza — APPROVED** [review]

**Comment by rberrelleza** [comment]
Thanks for the collaboration @kingdonb ! If this change is decoupled from helm operator, we can do them in two different PRs. I'll wait for your advice on how to proceed.

**Review by pchico83 — COMMENTED** [review]
@kingdonb awesome, thanks!

**Comment by kingdonb** [comment]
I need to start watching github notifications closer, I missed this :)

That's great! I don't remember what I got hung up on testing the helm operator upgrade, or if I just didn't try it myself

**Pull request merged**
