### PR TITLE
Use a init container instead of a job in movies sample

### PR DESCRIPTION
**Pull request by pchico83**

### CODE REVIEW

**Comment by pchico83** [comment]
@rberrelleza the job creates a pod that does not appear in a our job, which is extremely confusing when it generates quota issues.

**Comment by rberrelleza** [comment]
@pchico83 init containers also don't appear on the UI right? And they also contribute to the quota confusion.  Maybe it's better to just move that call to the API? (and maybe add a readiness probe to avoid the container "erroring out" while the DB is coming up.

**Comment by pchico83** [comment]
@rberrelleza they consume quota, but it is sequential.
`init` consumes 0.5cpu, then it finishes and frees the quota, then main container consumes 0.5cpu... the UI shows 0.5cpu all the time

**Comment by rberrelleza** [comment]
> @rberrelleza they consume quota, but it is sequential.
> `init` consumes 0.5cpu, then it finishes and frees the quota, then main container consumes 0.5cpu... the UI shows 0.5cpu all the time

ok. can you put readiness checks on the init container, or retry if mongo is not ready? I'd prefer the api doesn't show up as failed for a while because mongodb is not ready. The gateway in OpenFaaS does the same, and it confuses a lot of people.

**Pull request merged**
