### PR TITLE
Keep previous chart versions

### PR DESCRIPTION
**Pull request by pchico83**
Keep the chart previous versions by merging the new repository index with the current one

### CODE REVIEW

**Review by rberrelleza — COMMENTED** [review]
This is going to cause having historical versions of all the charts, is that what we want? This might cause issues in OE deployments.

**Review by rberrelleza — APPROVED** [review]

**Comment by pchico83** [comment]
@rberrelleza why could it cause issues on OE deployments?

**Comment by rberrelleza** [comment]
Because of 

> @rberrelleza why could it cause issues on OE deployments?

because of CRDs, changes in the default dev role, that sort of things.

**Comment by pchico83** [comment]
@rberrelleza how is that related to this PR?

**Comment by pchico83** [comment]
@rberrelleza merging this while we move the stacks chart from this repo, or remove that dependency.
But we need a way to version the chart for now.

**Pull request merged**
