### PR TITLE
Add dev env

### PR DESCRIPTION
**Pull request by rberrelleza**

### CODE REVIEW

**Comment by rberrelleza** [comment]
@pchico83 I think this is a good example for using build args during push. In this case, the namespace needs to be the current namespace (because `make all` needs to know the public URL).  how would you make this escenario portable?

**Comment by pchico83** [comment]
@rberrelleza we could set default build args, like the namespace or the URL.
You can also do:
```
push:
    args:
        - URL:$URL
```
Another option is to support build args in the okteto push cli.

**Comment by rberrelleza** [comment]
> @rberrelleza we could set default build args, like the namespace or the URL.
> You can also do:
> 
> ```
> push:
>     args:
>         - URL:$URL
> ```
> 
> Another option is to support build args in the okteto push cli.

that works. are we going to interpolate env vars in args too @pchico83 ?

**Comment by pchico83** [comment]
@rberrelleza yeap. I will add it to the docs too

**Pull request merged**
